items:
- uid: System.Net.NetworkInformation.PingException
  commentId: T:System.Net.NetworkInformation.PingException
  id: PingException
  parent: System.Net.NetworkInformation
  children:
  - System.Net.NetworkInformation.PingException.#ctor(System.String)
  - System.Net.NetworkInformation.PingException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  - vb
  name: PingException
  fullName: System.Net.NetworkInformation.PingException
  type: Class
  source:
    remote:
      path: src/System.Net.Ping/src/System/Net/NetworkInformation/PingException.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: PingException
    path: src/System.Net.Ping/src/System/Net/NetworkInformation/PingException.cs
    startLine: 6
  assemblies:
  - System.Net.Ping
  namespace: System.Net.NetworkInformation
  summary: "\n<p>The exception that is thrown when a <see cref=\"Overload:System.Net.NetworkInformation.Ping.Send\"></see> or <see cref=\"Overload:System.Net.NetworkInformation.Ping.SendAsync\"></see> method calls a method that throws an exception.</p>\n"
  remarks: "\n<p>The <xref href=\"System.Net.NetworkInformation.Ping\" data-throw-if-not-resolved=\"false\"></xref> class throws this exception to indicate that while sending an Internet Control Message Protocol (ICMP) Echo request, a method called by the <xref href=\"System.Net.NetworkInformation.Ping\" data-throw-if-not-resolved=\"false\"></xref> class threw an unhandled exception. Applications should check the inner exception of a <xref href=\"System.Net.NetworkInformation.PingException\" data-throw-if-not-resolved=\"false\"></xref> object to identify the problem. </p>\n<p>The <xref href=\"System.Net.NetworkInformation.Ping\" data-throw-if-not-resolved=\"false\"></xref> class does not throw this exception if the ICMP Echo request fails because of network, ICMP, or destination errors. For such errors, the <xref href=\"System.Net.NetworkInformation.Ping\" data-throw-if-not-resolved=\"false\"></xref> class returns a <xref href=\"System.Net.NetworkInformation.PingReply\" data-throw-if-not-resolved=\"false\"></xref> object with the relevant <xref href=\"System.Net.NetworkInformation.IPStatus\" data-throw-if-not-resolved=\"false\"></xref> value set in the <xref href=\"System.Net.NetworkInformation.PingReply.Status\" data-throw-if-not-resolved=\"false\"></xref> property. </p>\n"
  syntax:
    content: 'public class PingException : InvalidOperationException'
    content.vb: >-
      Public Class PingException
          Inherits InvalidOperationException
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: System.Net.NetworkInformation.PingException.#ctor(System.String)
  commentId: M:System.Net.NetworkInformation.PingException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Net.NetworkInformation.PingException
  langs:
  - csharp
  - vb
  name: PingException(String)
  fullName: System.Net.NetworkInformation.PingException.PingException(System.String)
  type: Constructor
  source:
    remote:
      path: src/System.Net.Ping/src/System/Net/NetworkInformation/PingException.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Net.Ping/src/System/Net/NetworkInformation/PingException.cs
    startLine: 8
  assemblies:
  - System.Net.Ping
  namespace: System.Net.NetworkInformation
  summary: "\n<p>Initializes a new instance of the <xref href=\"System.Net.NetworkInformation.PingException\" data-throw-if-not-resolved=\"false\"></xref> class using the specified message.</p>\n"
  remarks: "\n<p>This constructor initializes the <xref href=\"System.Exception.Message\" data-throw-if-not-resolved=\"false\"></xref> property with the text in the <em>message</em> parameter. The <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref> property is set to <strong>null</strong>. </p>\n"
  syntax:
    content: public PingException(string message)
    content.vb: Public Sub New(message As String)
    parameters:
    - id: message
      type: System.String
      description: "\n<p>A <xref href=\"System.String\" data-throw-if-not-resolved=\"false\"></xref> that describes the error.</p>\n"
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.Net.NetworkInformation.PingException.#ctor(System.String,System.Exception)
  commentId: M:System.Net.NetworkInformation.PingException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Net.NetworkInformation.PingException
  langs:
  - csharp
  - vb
  name: PingException(String, Exception)
  fullName: System.Net.NetworkInformation.PingException.PingException(System.String, System.Exception)
  type: Constructor
  source:
    remote:
      path: src/System.Net.Ping/ref/System.Net.Ping.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Net.Ping/ref/System.Net.Ping.cs
    startLine: 52
  assemblies:
  - System.Net.Ping
  namespace: System.Net.NetworkInformation
  summary: "\n<p>Initializes a new instance of the <xref href=\"System.Net.NetworkInformation.PingException\" data-throw-if-not-resolved=\"false\"></xref>  class using the specified message and inner exception.</p>\n"
  remarks: "\n<p>This constructor initializes the <xref href=\"System.Exception.Message\" data-throw-if-not-resolved=\"false\"></xref> property with the text in the <em>message</em> parameter, and the <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref> property with the <em>innerException</em> parameter.</p>\n"
  syntax:
    content: public PingException(string message, Exception innerException)
    content.vb: Public Sub New(message As String, innerException As Exception)
    parameters:
    - id: message
      type: System.String
      description: "\n<p>A <xref href=\"System.String\" data-throw-if-not-resolved=\"false\"></xref> that describes the error.</p>\n"
    - id: innerException
      type: System.Exception
      description: "\n<p>The exception that causes the current exception.</p>\n"
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: System.Net.NetworkInformation
  isExternal: false
  name: System.Net.NetworkInformation
  fullName: System.Net.NetworkInformation
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: false
  name: String
  fullName: System.String
- uid: System.Exception
  parent: System
  isExternal: false
  name: Exception
  fullName: System.Exception
