items:
- uid: System.DllNotFoundException
  id: DllNotFoundException
  parent: System
  children:
  - System.DllNotFoundException.#ctor
  - System.DllNotFoundException.#ctor(System.String)
  - System.DllNotFoundException.#ctor(System.String,System.Exception)
  href: System.DllNotFoundException.yml
  name: DllNotFoundException
  fullName: System.DllNotFoundException
  type: Class
  source:
    remote: &o0
      path: src/mscorlib/src/System/DllNotFoundException.cs
      branch: master
      repo: https://github.com/dotnet/coreclr.git
    path: src/mscorlib/src/System/DllNotFoundException.cs
    startLine: 17
  assemblies:
  - System.Runtime.InteropServices
  namespace: System
  summary: The exception that is thrown when a DLL specified in a DLL import cannot be found.
  syntax:
    content: 'public class DllNotFoundException : TypeLoadException'
    content.vb: Public Class DllNotFoundException Inherits TypeLoadException
  inheritance:
  - System.Object
- uid: System.DllNotFoundException.#ctor
  id: '#ctor'
  parent: System.DllNotFoundException
  href: System.DllNotFoundException.yml
  name: DllNotFoundException()
  fullName: System.DllNotFoundException.DllNotFoundException()
  type: Constructor
  source:
    remote: *o0
    path: src/mscorlib/src/System/DllNotFoundException.cs
    startLine: 19
  assemblies:
  - System.Runtime.InteropServices
  namespace: System
  summary: Initializes a new instance of the @'System.DllNotFoundException' class with default properties.
  syntax:
    content: public DllNotFoundException()
    content.vb: Public Sub New
- uid: System.DllNotFoundException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.DllNotFoundException
  href: System.DllNotFoundException.yml
  name: DllNotFoundException(String)
  fullName: System.DllNotFoundException.DllNotFoundException(System.String)
  type: Constructor
  source:
    remote: *o0
    path: src/mscorlib/src/System/DllNotFoundException.cs
    startLine: 24
  assemblies:
  - System.Runtime.InteropServices
  namespace: System
  summary: Initializes a new instance of the @'System.DllNotFoundException' class with a specified error message.
  syntax:
    content: public DllNotFoundException(string message)
    content.vb: Public Sub New(message As String)
    parameters:
    - id: message
      type: System.String
      description: The error message that explains the reason for the exception.
- uid: System.DllNotFoundException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.DllNotFoundException
  href: System.DllNotFoundException.yml
  name: DllNotFoundException(String, Exception)
  fullName: System.DllNotFoundException.DllNotFoundException(System.String, System.Exception)
  type: Constructor
  source:
    remote: *o0
    path: src/mscorlib/src/System/DllNotFoundException.cs
    startLine: 29
  assemblies:
  - System.Runtime.InteropServices
  namespace: System
  summary: Initializes a new instance of the @'System.DllNotFoundException' class with a specified error message and a reference to the inner exception that is the cause of this exception.
  syntax:
    content: public DllNotFoundException(string message, Exception inner)
    content.vb: Public Sub New(message As String, inner As Exception)
    parameters:
    - id: message
      type: System.String
      description: The error message that explains the reason for the exception.
    - id: inner
      type: System.Exception
      description: The exception that is the cause of the current exception. If the *inner* parameter is not null, the current exception is raised in a catch block that handles the inner exception.
references:
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Object
  parent: System
  isExternal: false
  href: System.Object.yml
  name: Object
  fullName: System.Object
- uid: System.String
  parent: System
  isExternal: false
  href: System.String.yml
  name: String
  fullName: System.String
- uid: System.Exception
  parent: System
  isExternal: false
  href: System.Exception.yml
  name: Exception
  fullName: System.Exception
